docker-image = "northstar-dedicated"
game-dir = "E:/titanfall2"

[defaults]
graphics-mode = "software"
tick-rate = 60
should-return-to-lobby = false
player-permissions = "none"
allow-insecure = true
report-to-master = false

[servers.tdm]
name = "TDM test"
description = "Testing"
playlist = "tdm"
mode = "tdm"
map = "mp_glitch"
match-timelimit = 0.5
