docker-image = "northstar-dedicated"
game-dir = "/titanfall"

[defaults]
graphics-mode = "software"
should-return-to-lobby = false
player-permissions = "none"
match-epilogue-enabled = false

[servers.everything]
name = "Playlist 24/7"
description = "A lil bit of everything"

[servers.slayer]
name = "Slayer 24/7"
description = "Always Slayer"
mode = "tdm"
map = "mp_glitch"
score-limit = 100
time-limit-minutes = 15

[servers.ffa]
name = "Free for all 24/7"
description = "Always free for all"
mode = "ffa"
map = "mp_drydock"
score-limit = 999
time-limit-minutes = 999
